# Generated by Django 5.0.14 on 2026-05-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('previous_scores', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('internet_access', models.IntegerField()),
                ('extra_activities', models.IntegerField()),
                ('family_support', models.IntegerField()),
                ('motivation_level', models.IntegerField()),
                ('prediction', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
